// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfryLYRY3OYL3wZD-gouI0mxISMFtGHB0',
    appId: '1:321643587751:web:6a18afeec1705899df1382',
    messagingSenderId: '321643587751',
    projectId: 'auth-8e24f',
    authDomain: 'auth-8e24f.firebaseapp.com',
    storageBucket: 'auth-8e24f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtn4NAeAP-8Gt69WTtRSWi4u4aRb8zeNg',
    appId: '1:321643587751:android:34e8e099e1885babdf1382',
    messagingSenderId: '321643587751',
    projectId: 'auth-8e24f',
    storageBucket: 'auth-8e24f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbAbaGFDx2OJN9UK68X0WyWTS7UL4fO8',
    appId: '1:321643587751:ios:ef573c9993ed2133df1382',
    messagingSenderId: '321643587751',
    projectId: 'auth-8e24f',
    storageBucket: 'auth-8e24f.appspot.com',
    iosBundleId: 'com.example.namerAppWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbAbaGFDx2OJN9UK68X0WyWTS7UL4fO8',
    appId: '1:321643587751:ios:ef573c9993ed2133df1382',
    messagingSenderId: '321643587751',
    projectId: 'auth-8e24f',
    storageBucket: 'auth-8e24f.appspot.com',
    iosBundleId: 'com.example.namerAppWeb',
  );
}
